import openapiTS, { astToString } from 'openapi-typescript';

export async function generateClient(document: string): Promise<string> {
  const generated =
    '// Generated by openapi-typescript. Do not edit.\n' + astToString(await openapiTS(document));
  return generated.replace(/\r\n/gu, '\n');
}
