import openapiTS, { astToString } from 'openapi-typescript';

export async function generateClient(document: string): Promise<string> {
  return (
    '// Generated by openapi-typescript. Do not edit.\n' + astToString(await openapiTS(document))
  );
}
